# Generated by Django 4.0.4 on 2022-05-20 07:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ck_main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillvalue',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
